//! PINNED recursion VERIFIER config — a SINGLE `RecursionConfig` for one operating point, so nothing
//! security-relevant (n_queries / pow_bits / blowup / fold_step / lifting / column shapes / roots) is
//! derived at prove or verify time. proving-utils turns it into the runtime form internally
//! (`build_recursion_precompute`). Regenerate for a different `k` with `scripts/regen_recursion_consts.sh
//! <k>` (runs `capture_all` + `scripts/gen_recursion_consts.py`).
//!
//! The pinned point is keyed by the public `(k, shots_per_shard)` — which fix `N` (`n_leaves`) and the
//! base-shard shape. The security params (`level1`/`fold` blocks, unpacker PCS) are k-INDEPENDENT; only
//! `leaf.root`, the `unpacker` root/columns/n_outputs, and `n_leaves` vary with `k`. main asserts the
//! run's `(k, shots, N)` match `CAPTURED_K`/`CAPTURED_SHOTS`/`CAPTURED_N` and panics (regenerate) otherwise.
//!
//! Captured at samples=9024, RC_LOG=25, base_blowup=1, fold_arity=8, node/leaf blowup=3.

use recursive_aggregate::pinned_configs::{
    PinnedComponentSizes, PinnedLayer, PinnedNodeLayer, PinnedUnpacker, RecursionConfig,
};
use stwo::core::fri::FriConfig;
use stwo::core::pcs::PcsConfig;

/// Fold arity `k`: each internal node verifies exactly this many children (`k`-to-1 fold). The
/// single source of truth for the arity (fold, unpacker preimage, in-circuit node hash). A level's
/// `len() % FOLD_ARITY` remainder is carried up unchanged.
pub const FOLD_ARITY: usize = 8;

/// Recursion (node-node / root) and leaf-wrap FRI blowup factor the pinned point was captured with.
/// Feeds the ~96-bit-secure `(pow_bits, n_queries)` table via `get_pcs_config`.
pub const RECURSION_LOG_BLOWUP: u32 = 3;

/// Gate count of the iadd256 benchmark circuit. Fixed to this circuit (NOT generalized to other
/// circuits); with `samples=9024` and the `2^26` GPU-resident row cap it sets `shots_per_shard`.
pub const N_GATES: usize = 2547;

/// Shots per base shard for fold repetitions `k`: `floor(2^26 / (k * N_GATES))` — the max shot count
/// whose trace fits the `2^26` GPU-resident row cap. `n_shards = ceil(samples / shots_per_shard)`.
pub fn shots_per_shard(k: usize) -> usize {
    (1usize << 26) / (k * N_GATES)
}

// <<GENERATED CONSTS BEGIN — this region is regenerated by scripts/gen_recursion_consts.py from the
// `capture_all` test output. Do not hand-edit.>>
//
// `CAPTURED_K`/`CAPTURED_SHOTS`/`CAPTURED_N`: the `(k, shots_per_shard)` the pinned `RECURSION_CONFIG`
// was captured for, and the resulting `n_leaves`. main asserts the run's `(k, shots, N)` match these.

pub const CAPTURED_K: usize = 2000;
pub const CAPTURED_SHOTS: usize = 13;
pub const CAPTURED_N: usize = 695;

pub const RECURSION_CONFIG: RecursionConfig = RecursionConfig {
    leaf: PinnedLayer {
        trace_log_size: 21,
        preprocessed_column_log_sizes: &[
            ("bitwise_xor_4_0", 8),
            ("bitwise_xor_4_1", 8),
            ("bitwise_xor_4_2", 8),
            ("bitwise_xor_7_0", 14),
            ("bitwise_xor_7_1", 14),
            ("bitwise_xor_7_2", 14),
            ("eq_in0_address", 16),
            ("eq_in1_address", 16),
            ("seq_16", 16),
            ("bitwise_xor_8_0", 16),
            ("bitwise_xor_8_1", 16),
            ("bitwise_xor_8_2", 16),
            ("triple_xor_input_addr_0", 18),
            ("triple_xor_input_addr_1", 18),
            ("triple_xor_input_addr_2", 18),
            ("triple_xor_output_addr", 18),
            ("triple_xor_multiplicity", 18),
            ("bitwise_xor_9_0", 18),
            ("bitwise_xor_9_1", 18),
            ("bitwise_xor_9_2", 18),
            ("m31_to_u32_input_addr", 19),
            ("m31_to_u32_output_addr", 19),
            ("m31_to_u32_multiplicity", 19),
            ("bitwise_xor_10_0", 20),
            ("bitwise_xor_10_1", 20),
            ("bitwise_xor_10_2", 20),
            ("qm31_ops_add_flag", 21),
            ("qm31_ops_sub_flag", 21),
            ("qm31_ops_mul_flag", 21),
            ("qm31_ops_pointwise_mul_flag", 21),
            ("qm31_ops_in0_address", 21),
            ("qm31_ops_in1_address", 21),
            ("qm31_ops_out_address", 21),
            ("qm31_ops_mults", 21),
            ("blake_g_gate_input_addr_a", 21),
            ("blake_g_gate_input_addr_b", 21),
            ("blake_g_gate_input_addr_c", 21),
            ("blake_g_gate_input_addr_d", 21),
            ("blake_g_gate_input_addr_f0", 21),
            ("blake_g_gate_input_addr_f1", 21),
            ("blake_g_gate_output_addr_a", 21),
            ("blake_g_gate_output_addr_b", 21),
            ("blake_g_gate_output_addr_c", 21),
            ("blake_g_gate_output_addr_d", 21),
            ("blake_g_gate_multiplicity", 21),
        ],
        root: [
            1671726266, 3079719153, 3369376636, 2214560819, 1590190948, 784830243, 1338047948,
            4269289402,
        ],
    },
    level1: PinnedNodeLayer {
        trace_log_size: 22,
        preprocessed_column_log_sizes: &[
            ("bitwise_xor_4_0", 8),
            ("bitwise_xor_4_1", 8),
            ("bitwise_xor_4_2", 8),
            ("bitwise_xor_7_0", 14),
            ("bitwise_xor_7_1", 14),
            ("bitwise_xor_7_2", 14),
            ("seq_16", 16),
            ("bitwise_xor_8_0", 16),
            ("bitwise_xor_8_1", 16),
            ("bitwise_xor_8_2", 16),
            ("eq_in0_address", 17),
            ("eq_in1_address", 17),
            ("bitwise_xor_9_0", 18),
            ("bitwise_xor_9_1", 18),
            ("bitwise_xor_9_2", 18),
            ("triple_xor_input_addr_0", 19),
            ("triple_xor_input_addr_1", 19),
            ("triple_xor_input_addr_2", 19),
            ("triple_xor_output_addr", 19),
            ("triple_xor_multiplicity", 19),
            ("m31_to_u32_input_addr", 20),
            ("m31_to_u32_output_addr", 20),
            ("m31_to_u32_multiplicity", 20),
            ("bitwise_xor_10_0", 20),
            ("bitwise_xor_10_1", 20),
            ("bitwise_xor_10_2", 20),
            ("qm31_ops_add_flag", 22),
            ("qm31_ops_sub_flag", 22),
            ("qm31_ops_mul_flag", 22),
            ("qm31_ops_pointwise_mul_flag", 22),
            ("qm31_ops_in0_address", 22),
            ("qm31_ops_in1_address", 22),
            ("qm31_ops_out_address", 22),
            ("qm31_ops_mults", 22),
            ("blake_g_gate_input_addr_a", 22),
            ("blake_g_gate_input_addr_b", 22),
            ("blake_g_gate_input_addr_c", 22),
            ("blake_g_gate_input_addr_d", 22),
            ("blake_g_gate_input_addr_f0", 22),
            ("blake_g_gate_input_addr_f1", 22),
            ("blake_g_gate_output_addr_a", 22),
            ("blake_g_gate_output_addr_b", 22),
            ("blake_g_gate_output_addr_c", 22),
            ("blake_g_gate_output_addr_d", 22),
            ("blake_g_gate_multiplicity", 22),
        ],
        roots: &[
            [
                1990614252, 494231903, 872668398, 1645072460, 3559864537, 1840174976, 1840493561,
                460461879,
            ],
            [
                1350136369, 613818072, 2389158623, 623563511, 762762034, 2941096340, 1306234309,
                781402198,
            ],
            [
                2826914180, 4169723737, 2593954969, 618739703, 3531112443, 1652306850, 3697541633,
                1374203952,
            ],
            [
                3535923161, 4048113930, 1160487281, 3545319893, 1011023218, 3048918468, 1762680830,
                1350636447,
            ],
            [
                2048057097, 2473932466, 1545952202, 94647821, 2688644939, 385238271, 686837108,
                3861452986,
            ],
            [
                3560555931, 2113360241, 2576210057, 3620827623, 2396287476, 2033049081, 3307246211,
                2834975683,
            ],
            [
                1066398071, 957931730, 2617037336, 4031838851, 626823415, 1208599359, 3889888060,
                3816771445,
            ],
        ],
    },
    fold: PinnedNodeLayer {
        trace_log_size: 22,
        preprocessed_column_log_sizes: &[
            ("bitwise_xor_4_0", 8),
            ("bitwise_xor_4_1", 8),
            ("bitwise_xor_4_2", 8),
            ("bitwise_xor_7_0", 14),
            ("bitwise_xor_7_1", 14),
            ("bitwise_xor_7_2", 14),
            ("seq_16", 16),
            ("bitwise_xor_8_0", 16),
            ("bitwise_xor_8_1", 16),
            ("bitwise_xor_8_2", 16),
            ("eq_in0_address", 17),
            ("eq_in1_address", 17),
            ("bitwise_xor_9_0", 18),
            ("bitwise_xor_9_1", 18),
            ("bitwise_xor_9_2", 18),
            ("triple_xor_input_addr_0", 19),
            ("triple_xor_input_addr_1", 19),
            ("triple_xor_input_addr_2", 19),
            ("triple_xor_output_addr", 19),
            ("triple_xor_multiplicity", 19),
            ("m31_to_u32_input_addr", 20),
            ("m31_to_u32_output_addr", 20),
            ("m31_to_u32_multiplicity", 20),
            ("bitwise_xor_10_0", 20),
            ("bitwise_xor_10_1", 20),
            ("bitwise_xor_10_2", 20),
            ("qm31_ops_add_flag", 22),
            ("qm31_ops_sub_flag", 22),
            ("qm31_ops_mul_flag", 22),
            ("qm31_ops_pointwise_mul_flag", 22),
            ("qm31_ops_in0_address", 22),
            ("qm31_ops_in1_address", 22),
            ("qm31_ops_out_address", 22),
            ("qm31_ops_mults", 22),
            ("blake_g_gate_input_addr_a", 22),
            ("blake_g_gate_input_addr_b", 22),
            ("blake_g_gate_input_addr_c", 22),
            ("blake_g_gate_input_addr_d", 22),
            ("blake_g_gate_input_addr_f0", 22),
            ("blake_g_gate_input_addr_f1", 22),
            ("blake_g_gate_output_addr_a", 22),
            ("blake_g_gate_output_addr_b", 22),
            ("blake_g_gate_output_addr_c", 22),
            ("blake_g_gate_output_addr_d", 22),
            ("blake_g_gate_multiplicity", 22),
        ],
        roots: &[
            [
                2035091519, 501705985, 166047172, 1123045752, 3568305265, 815574077, 3278034143,
                243510273,
            ],
            [
                1205184393, 1768923835, 1951434286, 589634634, 1735120075, 2299869867, 1464856437,
                2015570009,
            ],
            [
                697049043, 4174700279, 879818794, 100854944, 3626372037, 2285919184, 1035665903,
                640249968,
            ],
            [
                3815544182, 1429541617, 1568851281, 503105286, 4267192809, 4058400151, 1111718947,
                579912664,
            ],
            [
                4078638528, 3540322400, 1438635665, 1114065282, 1562653426, 1810740466, 1059032829,
                4099962379,
            ],
            [
                1954138946, 1856729758, 1748132318, 875692421, 2985527280, 2727902775, 397876993,
                3419958345,
            ],
            [
                821842364, 2771518357, 3999513413, 3904203972, 436240095, 516791821, 817970496,
                1661073348,
            ],
        ],
    },
    node_target: PinnedComponentSizes {
        eq: 131072,
        qm31_ops: 4194304,
        m31_to_u32: 1048576,
        triple_xor: 524288,
        blake_g_gate: 4194304,
    },
    unpacker: PinnedUnpacker {
        pcs: PcsConfig {
            pow_bits: 27,
            fri_config: FriConfig {
                log_blowup_factor: 3,
                log_last_layer_degree_bound: 0,
                n_queries: 23,
                fold_step: 4,
            },
            lifting_log_size: Some(23),
        },
        n_outputs: 5560,
        preprocessed_column_log_sizes: &[
            ("bitwise_xor_4_0", 8),
            ("bitwise_xor_4_1", 8),
            ("bitwise_xor_4_2", 8),
            ("eq_in0_address", 14),
            ("eq_in1_address", 14),
            ("bitwise_xor_7_0", 14),
            ("bitwise_xor_7_1", 14),
            ("bitwise_xor_7_2", 14),
            ("triple_xor_input_addr_0", 16),
            ("triple_xor_input_addr_1", 16),
            ("triple_xor_input_addr_2", 16),
            ("triple_xor_output_addr", 16),
            ("triple_xor_multiplicity", 16),
            ("seq_16", 16),
            ("bitwise_xor_8_0", 16),
            ("bitwise_xor_8_1", 16),
            ("bitwise_xor_8_2", 16),
            ("m31_to_u32_input_addr", 17),
            ("m31_to_u32_output_addr", 17),
            ("m31_to_u32_multiplicity", 17),
            ("bitwise_xor_9_0", 18),
            ("bitwise_xor_9_1", 18),
            ("bitwise_xor_9_2", 18),
            ("qm31_ops_add_flag", 19),
            ("qm31_ops_sub_flag", 19),
            ("qm31_ops_mul_flag", 19),
            ("qm31_ops_pointwise_mul_flag", 19),
            ("qm31_ops_in0_address", 19),
            ("qm31_ops_in1_address", 19),
            ("qm31_ops_out_address", 19),
            ("qm31_ops_mults", 19),
            ("blake_g_gate_input_addr_a", 20),
            ("blake_g_gate_input_addr_b", 20),
            ("blake_g_gate_input_addr_c", 20),
            ("blake_g_gate_input_addr_d", 20),
            ("blake_g_gate_input_addr_f0", 20),
            ("blake_g_gate_input_addr_f1", 20),
            ("blake_g_gate_output_addr_a", 20),
            ("blake_g_gate_output_addr_b", 20),
            ("blake_g_gate_output_addr_c", 20),
            ("blake_g_gate_output_addr_d", 20),
            ("blake_g_gate_multiplicity", 20),
            ("bitwise_xor_10_0", 20),
            ("bitwise_xor_10_1", 20),
            ("bitwise_xor_10_2", 20),
        ],
        root: [
            3703613476, 3482821825, 2797341073, 3706339720, 760043064, 2712616523, 1917170430,
            2259292315,
        ],
    },
    recursion_log_blowup: RECURSION_LOG_BLOWUP,
    leaf_log_blowup: RECURSION_LOG_BLOWUP,
    fold_arity: FOLD_ARITY,
    n_leaves: 695,
};
// <<GENERATED CONSTS END>>

// PINNED recursion-const capture + per-layer DRIFT tests (box-only, `#[ignore]`d); they rebuild the
// REAL per-layer verifier config and assert it equals the pinned consts.
#[cfg(test)]
#[path = "recursion_consts_tests.rs"]
mod recursion_consts_tests;
